---
title: "Challenge 1 - Detecting and Preventing Customer Churn"
output:
  html_document:
    df_print: paged
---


## Load Library
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
```


## Import Data
```{r}
churn <- read_csv("Churn_training.csv") %>% clean_names()
churn_kaggle <- read_csv("Churn_holdout.csv") %>% clean_names()

head(churn)
churn %>% skimr::skim()
```


## Explore Target
```{r}
churn_summary <- churn %>%
  count(churn) %>%
  mutate(pct = n/sum(n))

churn_summary %>%
  ggplot(aes(x = factor(churn), y = pct)) +
  geom_col() +
  geom_text(aes(label = round(pct*100, 1)), vjust = 2.5, color = "white") +
  labs(title = "Churn Possibility", x = "Churn", y = "Pct")

churn %>%
  ggplot(aes(x = network_speed, fill = factor(churn))) +
  geom_bar() +
  labs(title = "Churn By Network Speed", x = "Network Speed", y = "Count")

churn %>%
  ggplot(aes(x = phone_model, fill = factor(churn))) +
  geom_bar() +
  coord_flip() +
  labs(title = "Churn By Phone Model", x = "Phone Model", y = "Count")

churn %>%
  ggplot(aes(x = paperless_billing, fill = factor(churn))) +
  geom_bar() +
  labs(title = "Churn By Paperless Billing", x = "Paperless Billing", y = "Count")

churn %>%
  ggplot(aes(x = factor(number_phones), fill = factor(churn))) +
  geom_bar() +
  labs(title = "Churn By Number of Phones", x = "Number of Phones", y = "Count")

churn %>%
  ggplot(aes(x = streaming_plan, fill = factor(churn))) +
  geom_bar() +
  labs(title = "Churn By Streaming Plan", x = "Streaming Plan", y = "Count")

churn %>%
  ggplot(aes(x = payment_method, fill = factor(churn))) +
  geom_bar() +
  labs(title = "Churn By Payment Method", x = "Payment Method", y = "Count")

churn %>%
  ggplot(aes(x = factor(late_payments), fill = factor(churn))) +
  geom_bar() +
  labs(title = "Churn By Late Payments", x = "Late Payments", y = "Count")
```


## Prepare Data
```{r}
churn_prep <- churn %>%
  mutate(churn = as.factor(churn)) %>%
  mutate_if(is.character, factor)

churn_kaggle <- churn_kaggle %>%
  mutate_if(is.character, factor)
```


## Partition Data
```{r}
set.seed(123)

x <- initial_split(churn_prep, prop = 0.7)
train <- training(x)
test <- testing(x)

sprintf("Train PCT : %1.2f%%", nrow(train)/nrow(churn) * 100)
sprintf("Test PCT : %1.2f%%", nrow(test)/nrow(churn) * 100)
```


## Define Recipe
```{r}
knn_recipe <- recipe(churn ~ total_billed + number_phones + paperless_billing + streaming_minutes + streaming_plan + prev_balance + monthly_minutes + late_payments + payment_method, data = train) %>%
  step_impute_median(all_numeric_predictors()) %>%
  step_scale(all_numeric_predictors()) %>%
  step_novel(all_nominal_predictors()) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors())

bake(knn_recipe %>% prep(), train, composition = "tibble")
```


## Define Model
```{r}
knn_model1 <- nearest_neighbor(neighbors = 7, weight_func = "optimal") %>%
  set_mode("classification") %>%
  set_engine("kknn")

knn_model2 <- nearest_neighbor(neighbors = 10, weight_func = "optimal") %>%
  set_mode("classification") %>%
  set_engine("kknn")

tree_model <- decision_tree(tree_depth = 10, min_n = 3) %>%
  set_mode("classification") %>%
  set_engine("rpart")
```


## Define Workflow & Fit
```{r, warning=FALSE}
knn_workflow1 <- workflow() %>%
  add_recipe(knn_recipe) %>%
  add_model(knn_model1) %>%
  fit(train)

knn_workflow2 <- workflow() %>%
  add_recipe(knn_recipe) %>%
  add_model(knn_model2) %>%
  fit(train)

tree_workflow <- workflow() %>%
  add_recipe(knn_recipe) %>%
  add_model(tree_model)

tree_workflow_fit <- tree_workflow %>% fit(train)
tree_workflow_fit
```


## Score the model
```{r}
knn_scored_train1 <- predict(knn_workflow1, train, type = "prob") %>%
  bind_cols(predict(knn_workflow1, train, type = "class")) %>%
  bind_cols(., train)

knn_scored_test1 <- predict(knn_workflow1, test, type = "prob") %>%
  bind_cols(predict(knn_workflow1, test, type = "class")) %>%
  bind_cols(., test)

knn_scored_train2 <- predict(knn_workflow2, train, type = "prob") %>%
  bind_cols(predict(knn_workflow2, train, type = "class")) %>%
  bind_cols(., train)

knn_scored_test2 <- predict(knn_workflow2, test, type = "prob") %>%
  bind_cols(predict(knn_workflow2, test, type = "class")) %>%
  bind_cols(., test)

tree_scored_train <- predict(tree_workflow_fit, train, type = "prob") %>%
  bind_cols(predict(tree_workflow_fit, train, type = "class")) %>%
  bind_cols(., train)

tree_scored_test <- predict(tree_workflow_fit, test, type = "prob") %>%
  bind_cols(predict(tree_workflow_fit, test, type = "class")) %>%
  bind_cols(., test)
```


## Metrics
```{r, warning=FALSE}
options(yardstick.event_first = FALSE)

knn_scored_train1 %>%
  metrics(churn, .pred_1, estimate = .pred_class) %>%
  mutate(part = "knn training") %>%
  bind_rows(knn_scored_test1 %>%
              metrics(churn, .pred_1, estimate = .pred_class) %>%
              mutate(part = "knn testing")) %>%
  filter(.metric %in% c('accuracy', 'roc_auc')) %>%
  pivot_wider(names_from = .metric, values_from = .estimate)

knn_scored_train2 %>%
  metrics(churn, .pred_1, estimate = .pred_class) %>%
  mutate(part = "knn training") %>%
  bind_rows(knn_scored_test2 %>%
              metrics(churn, .pred_1, estimate = .pred_class) %>%
              mutate(part = "knn testing")) %>%
  filter(.metric %in% c('accuracy', 'roc_auc')) %>%
  pivot_wider(names_from = .metric, values_from = .estimate)

tree_scored_train %>%
  metrics(churn, .pred_1, estimate = .pred_class) %>%
  mutate(part = "tree training") %>%
  bind_rows(tree_scored_test %>%
              metrics(churn, .pred_1, estimate = .pred_class) %>%
              mutate(part = "tree testing")) %>%
  filter(.metric %in% c('accuracy', 'roc_auc')) %>%
  pivot_wider(names_from = .metric, values_from = .estimate)
```


## KNN Precision & Recall
```{r}
# -- knn 1
knn_scored_train1 %>%
  precision(churn, .pred_class) %>%
  mutate(part = "knn training") %>%
  bind_rows(knn_scored_test1 %>%
              precision(churn, .pred_class) %>%
              mutate(part = "knn testing"))

knn_scored_train1 %>%
  recall(churn, .pred_class) %>%
  mutate(part = "training") %>%
  bind_rows(knn_scored_test1 %>%
              recall(churn, .pred_class) %>%
              mutate(part = "testing"))

# -- knn 2
knn_scored_train2 %>%
  precision(churn, .pred_class) %>%
  mutate(part = "knn training") %>%
  bind_rows(knn_scored_test2 %>%
              precision(churn, .pred_class) %>%
              mutate(part = "knn testing"))

knn_scored_train2 %>%
  recall(churn, .pred_class) %>%
  mutate(part = "training") %>%
  bind_rows(knn_scored_test2 %>%
              recall(churn, .pred_class) %>%
              mutate(part = "testing"))
```


## KNN Confusion Matrix
```{r}
# -- knn 1
knn_scored_train1 %>%
  conf_mat(truth = churn, estimate = .pred_class, dnn = c("Prediction", "Truth")) %>%
  autoplot(type = "heatmap") +
  labs(title = "KNN 1 Training Confusion Matrix")

knn_scored_test1 %>%
  conf_mat(truth = churn, estimate = .pred_class, dnn = c("Prediction", "Truth")) %>%
  autoplot(type = "heatmap") +
  labs(title = "KNN 1 Testing Confusion Matrix")

# -- knn 2
knn_scored_train2 %>%
  conf_mat(truth = churn, estimate = .pred_class, dnn = c("Prediction", "Truth")) %>%
  autoplot(type = "heatmap") +
  labs(title = "KNN 2 Training Confusion Matrix")

knn_scored_test2 %>%
  conf_mat(truth = churn, estimate = .pred_class, dnn = c("Prediction", "Truth")) %>%
  autoplot(type = "heatmap") +
  labs(title = "KNN 2 Testing Confusion Matrix")
```


## Tree Confusion Matrix
```{r}
tree_scored_train %>%
  conf_mat(truth = churn, estimate = .pred_class, dnn = c("Prediction", "Truth")) %>%
  autoplot(type = "heatmap") +
  labs(title = "Training Confusion Matrix")

tree_scored_test %>%
  conf_mat(truth = churn, estimate = .pred_class, dnn = c("Prediction", "Truth")) %>%
  autoplot(type = "heatmap") +
  labs(title = "Training Confusion Matrix")
```


## Kaggle
```{r}
scored_kaggle <- predict(knn_workflow2, churn_kaggle, type = "class") %>%
  bind_cols(., churn_kaggle) %>%
  select(customer_id, churn = .pred_class)

scored_kaggle %>%
  write_csv("my_kaggle_submission.csv")
```

